apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service
        image: akhilmittal510/account-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_DB
          value: banking
        - name: PYTHONPATH
          value: "/app/account-service"
        - name: OTEL_LOG_LEVEL
          value: DEBUG
        - name: OTEL_EXPORTER_JAEGER_ENDPOINT
          value: "http://jaeger-collector.tracing:14268/api/traces"
        - name: OTEL_SERVICE_NAME
          value: "account-service"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
              
