apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: bank
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  selector: 
    app: account-service
  ports:
    - name: http
      port: 80
      targetPort: 8081
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: bank
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8083"
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  selector: 
    app: transaction-service
  ports:
    - name: http
      port: 80
      targetPort: 8083
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: bank
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8082"
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  selector: 
    app: auth-service
  ports:
    - name: http
      port: 80
      targetPort: 8082
      protocol: TCP